name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Sing APK
      run: |
         sudo apt install git
         git clone https://github.com/kirillsvc/signapk
         cd signapk
         cp ../app/build/outputs/apk/debug/app-debug.apk $PWD
         java -jar signapk.jar testkey.x509.pem testkey.pk8 app-debug.apk app-debug-signed.apk
         cd ../

    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: signapk/app-debug-signed.apk
